services:

  _defaults:
    autowire: true

  batch.handler:
    class: 'Monolog\Handler\RotatingFileHandler'
    arguments:
      $filename: '%kernel.logs_dir%/kaliop_batch.log'
      $maxFiles: 10
      $level: 200

  batch.logger:
    class: 'Monolog\Logger'
    arguments:
      $name: 'kaliop_batch'
      $handlers:
        - '@batch.handler'

  Kaliop\BatchBundle\Command\BatchCommand:
    arguments:
      $logger: '@batch.logger'
    tags:
      - { name: 'console.command' }

  Kaliop\BatchBundle\Command\JobsListBatchCommand:
    arguments:
      $logger: '@batch.logger'
    tags:
      - { name: 'console.command' }

  batch.entity_writer:
    class: 'Kaliop\BatchBundle\Batch\Writer\EntityWriter'
