services:

  _defaults:
    autowire: true

  batch.handler:
    class: 'Monolog\Handler\RotatingFileHandler'
    arguments:
      $filename: '%kernel.logs_dir%/kaliop_batch.log'
      $maxFiles: 10
      $level: 300

  batch.logger:
    class: 'Monolog\Logger'
    arguments:
      $name: 'kaliop_batch'
      $handlers:
        - '@batch.handler'

  batch.command:
    class: 'Kaliop\BatchBundle\Command\BatchCommand'
    tag:
      - { name: 'console.command' }

  batch.entity_writer:
    class: 'Kaliop\BatchBundle\Batch\Writer\EntityWriter'
